# Change these first
owner: palet-global # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Palet
    url: https://palet.app
    icon: https://cdn-1.palet.app/public/favicon.png
    assignees:
      - agnelnieves
  - name: Palet API
    url: https://api.palet.app/v0.1.0/healthcheck
    icon: https://cdn-1.palet.app/public/icons/api-connector.png
    assignees:
      - stevenlriv
  - name: Palet Global Compute
    check: "tcp-ping"
    url: 159.203.151.174
    icon: https://cdn-1.palet.app/public/icons/neuro-network.png
    port: 7500
    assignees:
      - stevenlriv

status-website:
  cname: status.palet.app
  logoUrl: https://cdn-1.palet.app/public/palet-logo-icon.svg
  favicon: https://cdn-1.palet.app/public/favicon.png
  name: Palet System Status
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Visit Palet
      href: https://palet.app
      
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
